create table location (id bigint generated by default as identity, city varchar(255) not null, lat double not null, lon double not null, state varchar(255) not null, primary key (id))
create table meteorology (id bigint not null, date date not null, id_location bigint, primary key (id))
create table temperatures (id bigint generated by default as identity, hour integer, id_meteorology bigint, temperature double, primary key (id))
alter table meteorology add constraint FKeepgkbxymhb950rymna9n6bl9 foreign key (id_location) references location
alter table temperatures add constraint FKbgxu3r5ki2vpvv5y7h49srw3a foreign key (id_meteorology) references meteorology
